### ISSUE TITLE
Utility functions should not be part of the standard

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#1]
We should keep the standard as short as possible. *Less is more.*
Here is a good example of a perfect specification: https://promisesaplus.com/
Basically, it defines the `.then()` functions and it's two arguments.

The utility functions described in [the original stampit issue](https://github.com/stampit-org/stampit/issues/151) should be purely implementation details.

Composables standard should define two things:
1) `.compose()` (and `compose()`) functions and its arguments.
2) The *stamp descriptor* object structure.

Discuss.

**Comment by ericelliott** [comment]
Agreed. We should definitely have the core utilities available as implementation examples, though. But all implementation examples should be in the stampit repo, or for the non-core utilities, their own repos. =)

**Comment by koresar** [comment]
By `stampit repo` you mean this repo? :)

**Comment by ericelliott** [comment]
No, I mean that stampit (the library) *is* the implementation example for the core functions. =)

**Comment by koresar** [comment]
Oh. :) I see. Now it's clear.

This is decided now. I'll leave this issue open for a while.

**Comment by ericelliott** [comment]
:+1:

**Comment by koresar** [comment]
Still, there is Eric's opinion that utilities must be part of the standard: https://github.com/stampit-org/stamp-specification/issues/9#issuecomment-123155300

I'm not sure if we have an agreement on that or not.

@ericelliott Please, do not close this issue untill all of us are on the same page.

**Comment by ericelliott** [comment]
> Still, there is Eric's opinion that utilities must be part of the standard: https://github.com/stampit-org/stamp-specification/issues/9#issuecomment-123155300

I don't think they should be part of the stamp descriptor standard, but if you insist on shaving keystrokes using only composables, there's no way around making the part of the stamp standard.

Every API decision involves sacrifices.

* If you insist on the short names, stamps will not become part of the JavaScript specification.
* If you insist on shortcuts with no import (until stamps are part of JS native), utility functions must be part of the composable spec.

Both of those requirements will make it harder to get native stamps without compromises we don't like.

So, pick your poison. Do you want native stamps, or do you want shortcuts on every stamp?

**Comment by koresar** [comment]
The short outcome of the discussion in a [different issue](https://github.com/stampit-org/stamp-specification/issues/9#issuecomment-124569603).

> 1) leave the long names
2) we rename "core utililities" to "optional extra utilities". Also can be referenced as "additional utilities" or "stampit utilities". The utilities should not be part of the standard, although can be referenced as "handy tools".
