### ISSUE TITLE
Specify details on how are things deeply merged

### ISSUE THREAD

**Issue by FredyC** [stampit-org/stamp-specification#101]
This is very vague here as it was simply assuming use of lodash. However in case someone wants to make their own implementation, it should be clearly specified how this merge behaves. Concretely with `stampit` which now uses own merge function, it does clone functions as a set of properties instead of referencing them (see [related issue](https://github.com/stampit-org/stampit/issues/217)).

I think that functions should be exception on deep cloning for sure. Do you have other opinion?

Might be also related to the Symbol support #86 which talks mainly about cloning Symbol when used instead of properties names. However Symbol reference should be kept intact even when used as value.

**Comment by koresar** [comment]
My mental model of stamps is following:
* The `compose()` (and `stamp.compose()`) function is just the metadata collection functions. It does nothing else but collecting metadata.
* Using the collected metadata user can create objects by calling the `stamp()`.

Thus, the metadata collection is the corner stone of the stamps philosophy. We should not limit people on how they merge metadata. I'm thinking of allowing people to overwrite the [`mergeComposable`](https://github.com/stampit-org/stamp-specification/blob/master/compose.js#L71) similar to the [initializers](https://github.com/stampit-org/stamp-specification/blob/master/compose.js#L38) way. In other words - if user specified a merging callback function and it returned non-undefined then use the returned value as a new descriptor. (Will provide code examples later.)

**Comment by FredyC** [comment]
One thing is metadata as bunch of primitives or even arrays, but function is something way different. As it cannot be cloned, it needs to stay in place untouched unless something else wants to put another kind of data in same spot (even another function). In that case it simply forgets completely about that function and new data are used. That's how lodash is doing it (see http://jsfiddle.net/ybem606s/3/).

I think we should adopt that behavior. It's something that sane person would expect. If you say to consumer "you need to override merger" then I believe most of people would just go away from it because it adds up another unwanted hassle for something trivial like this.

**Comment by koresar** [comment]
Totally agree with that. I will fix the merger later this week (sorry, busy). But yeah, functions should not be treated as a mergable objects.

**Comment by FredyC** [comment]
Well this issue isn't about fixing merger here, but to actually expand specification and say how is deep merging behaving.

**Comment by koresar** [comment]
Okay, here is the proposed merging algorithm /cc @ericelliott @unstoppablecarl @troutowicz 

-----
1. Plain objects are deeply merged.
2. Array are concatenated.
3. Everything else (including Symbols) is copied by assignment.

-----
The first two are already part of the specs. The third item is the new addition.

Opinions?

**Comment by koresar** [comment]
Since there are no objections I'll implement exactly that.

**Comment by FredyC** [comment]
I definitely agree with it. Just encountered another use case where my function disappeared after merge.
