### ISSUE TITLE
Allow metadata (descriptors) merging override

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#102]
My mental model of stamps is following:
* The `compose()` (and `stamp.compose()`) function is just the metadata collection functions. It does nothing else but collecting metadata.
* Using the collected metadata user can create objects by calling the `stamp()`.

Thus, the metadata collection is the corner stone of the stamps philosophy. **We should not limit people on how they merge metadata.**

I'm thinking of allowing people to overwrite the [`mergeComposable`](https://github.com/stampit-org/stamp-specification/blob/078643bd27d5e19e083be19f617a9c291dc08f25/compose.js#L147) similar to the [initializers](https://github.com/stampit-org/stamp-specification/blob/078643bd27d5e19e083be19f617a9c291dc08f25/compose.js#L100) way. In other words - if user specified a merging callback function and it returned non-undefined then use the returned value as a new descriptor. (Will provide code examples later.)

**Comment by ericelliott** [comment]
Be careful not to over-complicate things...

Make sure you answer "is this really needed?" =)

**Comment by koresar** [comment]
I'm yet to need this in JS. Although, it might be useful for other languages.

This idea needs a deep thought though.

**Comment by unstoppablecarl** [comment]
I cannot think of a use case that could not be solved by init

**Comment by koresar** [comment]
yes.  Either `init` or [infected compose](https://medium.com/@koresar/fun-with-stamps-episode-8-tracking-and-overriding-composition-573aa85ba622).

I'm just thinking of other languages. It could be useful there. Could not. :)

**Comment by koresar** [comment]
Code example as promised:
```js
const WrappedMergeStamp = compose({
  mergeDescriptor(dstDescriptor, srcDescriptor) {
    // my own algorithm to merge metadata.
    console.log(src);
    // Can wrap original compose.
    return Object.assign({}, compose(dst, src).compose);
  }
});

WrappedMergeStamp.compose({ properties: { a: 1 } }).compose({ methods: { b() {} } });
```
Will print:
```
{ properties: { a: 1 } }
{ methods: { b: [Function: b] } }
```

Again. I don't see JS need that given that we have infected compose.
But other languages are not as flexible (e.g. Java or C#).

**Comment by koresar** [comment]
This idea was continued with the #109 proposal.
Closing.
