### ISSUE TITLE
Should static methods/props be assigned to a stamp's prototype?

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#104]
This is an open question. I have no strong opinion on that yet.

Sometime some tools check prototype of a class/function/component/stamp/etc. For example:

``` js
function isReactComponent(component) {
  return typeof component.prototype.render === 'function';
}
```

This would always return `false` for regular stamps. There is no standard way to attach anything to a stamp's prototype.

There are two solutions to this:
1. Standardize that `methods` are also assigned as a stamp's `.prototype`. Or,
2. Do not change anything and advise people to use [infected compose](https://medium.com/@koresar/fun-with-stamps-episode-8-tracking-and-overriding-composition-573aa85ba622#.v2vdvbt61) for that need.

---

Currently, I'm inclined towards the second solution. 

It would be great to hear React devs opinion.

**Comment by FredyC** [comment]
I am not really sure that it should be statics that go to `prototype`. Why? Even mentioned `render` method is not static one, it's instance method.

**Comment by koresar** [comment]
@FredyC My late evening mind tricked me. Thank you for clarification. I've updated the issue. Now, it's says "methods" instead of "statics". Sorry about that.

**Comment by JosephClay** [comment]
Explicitly checking the prototype for something is bad practice IMO. Instead of seeing if the instance has the method, it's looking for the object to _have a specific structure_ and the method.

Also, checking the instance for a top-level method will check the prototype chain.

Vote for 2

**Comment by koresar** [comment]
This is not about instance checking @JosephClay 
```
> function F(){}
> F.prototype.render = function render(){};
> console.log(F.render);
undefined
```
This is about _constructor structure check_.

You are probably confusing `instance.__proto__` with a special `ConstructorFunction.protoype` object.

So, those tools I mentioned is checking `Constructor.prototype` but not `instance.__proto__`

**Comment by unstoppablecarl** [comment]
What specific tool is checking for that? I would think this is poor practice in general.

**Comment by koresar** [comment]
Yeah, it might not work with react HOC's for example.
@FredyC can you remind which tool you stumbled upon?

**Comment by FredyC** [comment]
It's [react-redux-provide](https://github.com/loggur/react-redux-provide/blob/d8ee63c2fa5fd9d4619d5bbaf2420cee8e1eded3/src/provide.js#L260)

**Comment by unstoppablecarl** [comment]
I don't think it will be possible to make them 'look' like classes. They are not classes. I think a use would need to make some sort of adapter implementation for those cases. Trying to get close to looking like a class based on assumptions of usage is probably not going to be helpful for those cases anyway.

**Comment by FredyC** [comment]
Yea, it's not really a pressing matter right now, this was only single case I've run into and so far doesn't seem relevant. Let's keep it open here in case we find some other reason for this.

**Comment by ericelliott** [comment]
If you assigned methods to `stamp.prototype` by identity, it would enable `instanceof` checks, which IMO, is a bad thing.

**Comment by FredyC** [comment]
I don't that works like that simply because stamp doesn't have a `constructor` property which is used for `instanceOf` check.

**Comment by ericelliott** [comment]
The `constructor` property is not involved at all in the `instanceof` check:

See my answer to [Confused about javascript prototypal inheritance](http://stackoverflow.com/questions/2182685/confused-about-javascript-prototypal-inheritance/37579135#37579135).

Verify for yourself:

```js
function foo() {}
var bar = { a: 'a'};
foo.prototype = bar; // Object {a: 'a'}
baz = Object.create(bar);
baz instanceof foo // true
```

Note: No `constructor` property anywhere...

**Comment by unstoppablecarl** [comment]
The constructor property is a developer convention added for convenience.

**Comment by FredyC** [comment]
Ok I did not know about that, thanks. 

Either way, let's keep it open here for now. Since this came from a react-stamp, it's more likely end up there and perhaps with just making copy of a `render` method on a prototype to fulfill basic needs to identify components.

**Comment by koresar** [comment]
Bad idea. :) No outcome. Closing the issue.
