### ISSUE TITLE
Out of sync docs

### ISSUE THREAD

**Issue by eladchen** [stampit-org/stamp-specification#108]
I think the docs for stamps init methods is out of date.

[This section](https://github.com/stampit-org/stampit/blob/master/docs/API.md#stampinitarg1-arg2-arg3) suggest that init methods are called with one argument, which is, an object containing 3 properties "instance", "stamp" & "args".

[While this section](https://github.com/stampit-org/stamp-specification#initializer-parameters) ( @stamp-specification repo ) suggest that init methods are called with two arguments, the first is "options"and the second is the same as the one described in the previous paragraph.

To make things even more clear, the first section describes this signature:

```js
( { instance: Object, stamp: Stamp, args: Array }) => instance: Object
```

While the second describes this signature:

```js
(options: Object, { instance: Object, stamp: Stamp, args: Array }) => instance: Object
```

Is this intentional? And if so, does it mean stampit version 2.x doesn't follow the specs ?

**Comment by koresar** [comment]
Thanks @eladchen !

You won't believe, but I'm working on that exactly right now. :)

Also, your first link is for stampit v2. Whereas only stampit v3 (coming soon) is compatible with stamp-specification.

Yes, stampit v2 does not follow the specs.

Do you have any other questions or suggestions?

**Comment by eladchen** [comment]
Oh cool.

> Do you have any other questions or suggestions?

1. Perhaps the fact version 2 doesn't follow the specs could be pointed out somewhere ?
2. I'm looking for a way to handle the collision of two properties in two different stamps with the same name ( ie, stampOne & stampTwo both have the same named property )  But I feel like this needs be in a different discussion. What do you think?

**Comment by koresar** [comment]
1. Will do right now.
2. Yeah. Feel free to open a new issue, or jump into the Gitter chat: https://gitter.im/stampit-org/stampit

Cheers! :)

Btw, the final stampt v3 PR is coming today. You might wanna join and review it. There are only docs change mainly. My English requires double checks usually as you might noticed. :)

**Comment by koresar** [comment]
v3 published. Docs in sync (except for the "advanced_exampled.md").
