### ISSUE TITLE
Looking for resources on Stamp

### ISSUE THREAD

**Issue by blachawk** [stampit-org/stamp-specification#119]
Hello, 
Would there be any reference online on defining why Stamp was created to begin with?  What is JavaScript not already doing, in which Stamp does well at?  Looking for any kind of read.

Thanks

**Comment by FredyC** [comment]
Well ... https://medium.com/@koresar/fun-with-stamps-episode-1-stamp-basics-e0627d81efe0

**Comment by koresar** [comment]
That's an awesome idea!
I gonna blog post about it.
Thanks

**Comment by koresar** [comment]
Btw, it was created as the website stampit.js.org
