### ISSUE TITLE
getter/setter cannot run

### ISSUE THREAD

**Issue by lornally** [stampit-org/stamp-specification#125]
i will fix it, now

**Comment by lornally** [comment]
you are welcome. cool, we have propertyDescriptors, and actually, we have it in stampit, do we replace it in stampit? and ask a digression from this issue, how can you react so in time? you can receive some github message?

**Comment by koresar** [comment]
Maybe Stamps should support getters and setters out of the box for every metadata. I've created this Request For Comments issue: https://github.com/stampit-org/stamp-specification/issues/127

I'm willing to implement it consistently.
* With full unit test coverage via [check-compose](https://github.com/stampit-org/stamp/tree/master/packages/check-compose)
* In stamp-specification (it's a example implementation), stampit (most used module) and @ stamp/it

**Comment by lornally** [comment]
i agree with you, i think getter/setter is a base require.   and i think now stamp-specification is not a really specification, because it is not simple enough, it is so complex and more  long-winded than stampit.
