### ISSUE TITLE
[RFC] Getters and Setters should be copied across with other metadata

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#127]
We get a request from other people to add getters/setters support often. I believe it's time to support them out of the box for: methods, properties, staticProperties, configuration, and all the "deep" metadata.

**Comment by lornally** [comment]
yes, right suggest:)

**Comment by koresar** [comment]
This was just released as Stamp Specification v1.6

Next up - the `stampit` module. :)
