### ISSUE TITLE
`compose()` function as optional extra

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#14]
The `compose()` king of the kings function bothers me more and more as I think of stampit 3.0. 
TL;DR: it should be "optional extra" part of the standard.

Take promises A+ as an example (again). :)
You might know that it does not say how you must create your objects, it just describes compatibility mechanism between many different promise implementations.
It should be Composables aim too.

Composables standard should promote compatibility. Whereas it should not enforce a module API.

I'm going to supply a PR which changes the README.md accordingly.

**Comment by koresar** [comment]
See #15

**Comment by ericelliott** [comment]
What's the purpose of calling "compose" optional?

Optional in what sense? Does this mean that composables are not required to supply a compose function? If so, we should clarify that.

**Comment by koresar** [comment]
Standalone "compose" should not be obligatory. The `.compose` method is not changed anyhow.
Also see my post above. It answers the question "why".

**Comment by ericelliott** [comment]
> Standalone "compose" should not be obligatory.

In what context? Do you mean that composables don't have to implement a standalone "compose" function? If so, we should say that explicitly rather than simply calling it "optional".

> The .compose method is not changed anyhow.

So all composables should have a `.compose()` method? Or would a `.compose` object suffice as a placeholder for the fixed properties?

**Comment by koresar** [comment]
> we should say that explicitly rather than simply calling it "optional".
Agree.

> So all composables should have a .compose() method? Or would a .compose object suffice as a placeholder for the fixed properties?
The method stays the way we agreen on it weeks ago. I'm not quite understanding the point of this question.

**Comment by ericelliott** [comment]
> The method stays the way we agreen on it weeks ago. I'm not quite understanding the point of this question.

The point is, does every composable really need `.compose` to be callable? Or could it just be an object with the specified fixed properties which is optionally a callable method?

**Comment by koresar** [comment]
We went the "composables path" mostly because we needed to minimize collision with static properties. 

Remiding you the issue of stampit, a person found that his stamp static method collisioned with stamp's own function.

**Comment by ericelliott** [comment]
Can we close this?
