### ISSUE TITLE
Stamp descriptor property names

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#2]
Currently proposed property names are:
>
* `methods` - A set of methods that will be added to the object's delegate prototype.
* `references` - A set of properties that will be added to new object instances by assignment.
* `deepProperties` - A set of properties that will be added to new object instances by assignment with deep property merge.
* `initializers` - A set of functions that will run in sequence and passed the data necessary to initialize a stamp instance.
* `staticProperties` - A set of static properties that will be copied by assignment to the stamp.
* `propertyDescriptors` - A set of [object property descriptors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties) used for fine-grained control over object property behaviors
* `configuration` - A set of options made available to the stamp and its initializers during object instance creation. Configuration properties get deep merged.

And then we have stamp creation via the `compose()` function:
```js
var stamp = compose({
  methods: ...
  assign: ...
  merge: ...
  ...
});
```

While implementing an [sample implementation](https://github.com/stampit-org/stamp-specification/blob/master/sample-implementation.js) of the composables standard I found it very hard to rename the properties back and forth. `assign <-> references`, `merge <-> deepProperties`, etc.

Also, it would be harder for people to match those in the head every time they come across a descriptor.
*Less is more.*

It doesn't help with code readability either.

I believe we should not have two names for an essentially same thing.

Let's have single short unified name for each of them (intentionally plural as well as in Present Sinple tense).
* methods
* statics
* assigns
* merges
* runs
* configs
* propertyDescriptors

**Comment by koresar** [comment]
When coding using stampit I mostly use `methods`, `assigns` and `runs`. I'd love these to be short named.

**Comment by ericelliott** [comment]
Don't rename back and forth. Build from scratch. These are breaking changes, and that's OK.

**Comment by koresar** [comment]
I mean there's renaming in the code. Like this:
```js
descriptor.references = stamp.assign;
descriptor.deepProperties = stamp.merge;
```
I need to avoid that kind of code. Something like that would be preferable:
```js
_.assign(descriptor, _.pick(stamp, ['assign', 'merge']));
```

Do you see what I mean?

**Comment by ericelliott** [comment]
The differences are nouns vs verbs.

A noun describes something that is.
A verb describes something that happens.

These are different words on purpose.

**Comment by ericelliott** [comment]
Keep in mind, since we're pushing for a standard, we don't just have to think about internal consistency with Stampit. We also have to think about consistency with the already built-in method and property names in the JavaScript specification. Your proposals for the following names are not consistent with JavaScript built-in naming conventions, which will make it very unlikely that the proposal will be accepted into the JS specification:

```js
statics
assigns
merges
runs
```

**Comment by koresar** [comment]
> Your proposals for the following names are not consistent with JavaScript built-in naming conventions

Would you reference the conventions please?

**Comment by koresar** [comment]
Superseeded with #9. Closing.
