### ISSUE TITLE
Pass configuration to initializers

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#22]
Should we pass `configuration` to the [initializers](https://github.com/stampit-org/stamp-specification#initializer-parameters)?

```js
compose({ 
  initializers({ configuration }) {
    console.log(configuration);
  }
});
```

Otherwise, how do I use the configuration? At what point of time?

**Comment by ericelliott** [comment]
Don't we already pass the stamp, and isn't configuration part of the stamp descriptor?

**Comment by koresar** [comment]
Yes, we do. So, to get to the `configuration` we should write `stamp.compose.configuration`.

Yeah. Lookig at it from the other side the simpler the better. Closing this one too. :)

**Comment by ericelliott** [comment]
:+1:
