### ISSUE TITLE
Pass options to stamp instead of baseObject

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/stamp-specification#23]
It's probably better for general purpose and long-term API stability to pass an options argument as the first parameter of a stamp instead of a baseObject. Then you could do:

```js
const myStamp = compose(events, behaviors, httpStream);
myStamp({ baseObject: foo, httpStream: { url: streamUrl } });
```

To get at the baseObject in the factory, we just add braces around the `{ baseObject }` parameter. Easy.

Comments?

**Comment by troutowicz** [comment]
The fewer arguments the better IMO. The `baseObject` is just as much an option as any other, so I think it fits nicely inside the options object.

**Comment by ericelliott** [comment]
:+1:

**Comment by JosephClay** [comment]
:+1: Wholeheartedly agree with @troutowicz

**Comment by koresar** [comment]
I'm considering this unnecessary overcomplication. KISS? And, less is more. Right?

From the text of the changes I didn't quite get the prototype replacement bit. When talking about code I prefer code. Could you please supply usage and implementation examples?

**Comment by ericelliott** [comment]
This doesn't complicate, it simplifies. Currently, if you want to pass params to init functions without passing a baseObject:

```js
const myStamp = compose(events, behaviors, httpStream);
myStamp(null, { httpStream: { url: streamUrl } });
```

vs, with this change:

```js
const myStamp = compose(events, behaviors, httpStream);
myStamp({ httpStream: { url: streamUrl } });
```

As for the prototype replacement bit, currently, if you want to pass a `baseObject`, you break prototype delegation:

```js
const myStamp = compose(
  methods({
    foo () {}
  })
);
const myObj = myStamp(baseObject);
myObj.hasOwnProperty(foo);  // true - no delegation
```

This means that any stamp relying on delegation behavior will break under the current spec. This behavior is also inconsistent with all previous versions of stampit.

We don't have to break delegation. The alternative is to create a new delegate object and set methods on that object (rough pseudocode):

```js
function factory ({ baseObject }) {
  let delegate;
  if (baseObject) {
    delegate = {};
    delegate.__proto__ = baseObject.__proto__;
    baseObject.__proto__ = delegate;
  }
}
```

**Comment by koresar** [comment]
I like the delegate of delegate idea. :)

**Comment by koresar** [comment]
Regarding the baseObject I'm still in frustration. 
This complication
`myStamp(null, { httpStream: { url: streamUrl } });` -> `myStamp({ httpStream: { url: streamUrl } });`
purpose is to remove this `null` only. 5 characters "simplification"?

But now, we are forcing people to write additional `{ baseObject: }`.
`myStamp({ myUrl: "1234" })` -> `myStamp({ baseObject: { myUrl: "1234" } })`
No so much of the simplification to me.

**Comment by koresar** [comment]
The `baseObject` property name may and will clash with stamp author properties.

**Comment by ericelliott** [comment]
We could call it `base` if you prefer.

Consider the first version of stampit. I thought, "gee, it would be great if people could just pass in default property settings as the first param" -- but it SUCKED because a lot of the time, that's not what people wanted to do.

So it is with `baseObject`. My need for `baseObject` is so infrequent, I don't even care if it's supported in stampit. For me it's an edge case that will bother me every time I type `null` so I can get to the options object that should have been the first param in the first place.

**Comment by ericelliott** [comment]
We can make it a reserved prop of the options object. It won't clash because stamp authors won't be allowed to try to use it.

**Comment by ericelliott** [comment]
Keep in mind, the `options` object does not set properties on the instance or the stamp. It's just a convenient way for stamp authors to pass options into stamps at instantiation time. Collisions are not a concern in this context.

**Comment by koresar** [comment]
I agree that sometimes people just don't need default properties. I'd even agree that this is true most of the time (similar to the classic OOP constructors).

Let's dicuss the `options` object. Anything else besides the `.base` property should not allow people to use?

**Comment by ericelliott** [comment]
Good question. `defaults` and `overrides` might be handy:

```js
const myObj = myStamp({
  defaults: { someProperty: true },
  overrides: { someOtherProperty: false }
}); // { someProperty: true, someOtherProperty: false }
```

This could behave like [the defaults/overrides pattern](https://gist.github.com/ericelliott/f3c2a53a1d4100539f71).

**Comment by koresar** [comment]
Okay. `defaults` seem good. What's that `overrides` is about? Can you elaborate with code examples, please. Thanks

**Comment by ericelliott** [comment]
`before` and `after` could also be useful:

```js
const myObj = myStamp({
  before ({ instance, stamp, args }) {
    const secret = 'Eric likes chocolate a little too much.';
    instance.getSecret = () => {
      return secret;
    }
    return instance;
  },
  after ({ instance, stamp, args }) {
    const secret = 'My secrets are mine to keep.'
    instance.getSecret = () => {
      return secret;
    }
  }
});
```

**Comment by koresar** [comment]
> If you need to do things that aren't supported by the default compose logic, you should do so in a stamp, not by adding complexity to the API.

> Any time you want to add features to an interface, you need to justify those features, because:
1. More API surface area means more room for bugs.
2. More room for bugs means more room for security hazards. In a lib, multiply this hazard by all apps using it.
3. More API surface area means more to learn. Sharper learning curve.
4. Sharper learning curve = more intimidating to new users.

> In other words, new features have both negative and (sometimes) positive impacts on that API.

> So the challenge isn't, "show me how to do this with the current API."

> The challenge is "show me valid use cases compelling enough to justify the costs."

> We should be looking for ways to *simplify* the stamp API, rather than ways to make it more complex.

**Comment by ericelliott** [comment]
> What's that overrides is about?

```js
const defaults = {
  foo: foo
};
const overrides = {};

if (process.env.foo) {
  overrides.foo = process.env.foo;
}

const myObj = myStamp({ defaults, overrides });
```

**Comment by koresar** [comment]
In the example above the `overrides` looks redundant. The following results the same.:
```js
const myObj = myStamp({ defaults, foo: process.env.foo });
```

**Comment by ericelliott** [comment]
No, it doesn't. `options` properties don't get added to the instance.

**Comment by koresar** [comment]
So, this example from the above is already irrelevant?
```js
const myStamp = compose(events, behaviors, httpStream);
myStamp({ httpStream: { url: streamUrl } });
```

**Comment by ericelliott** [comment]
No, the `httpStream` stamp could have logic that grabs the url from the `options` object in order to establish the connection. It never sets that URL as an instance property.

**Comment by ericelliott** [comment]
If you *want* that behavior in your stamp, you could of course grab the relevant props from `options` and set them on the stamp. This idea is about empowering stamp authors so that they have more control over the stamp's API.

Currently, we're cramming the `baseObject` concept down the throats of users, whether they like it or not. `options` fixes that problem.

**Comment by koresar** [comment]
You should have examplained that code-wise. :)

So, I'm eager to hear what's your opinion on this: https://github.com/stampit-org/stamp-specification/issues/23#issuecomment-137294331

**Comment by ericelliott** [comment]
> Re: not by adding complexity to the API.

We're not adding complexity. We're removing complexity. That is a worthy goal in and of itself. As for the "reserved" options, I think that we can justify those. At the very least, we can justify reserving a few words in case we want to add them later. =)

**Comment by ericelliott** [comment]
I'd like to add the reserved words we've discussed, but we can do that stuff in a separate PR, and have separate discussions about them. For now, assume that `base` is the only thing we're discussing in this thread, for the currently open PR.

**Comment by koresar** [comment]
Can you please open a new thread to discuss the reserved words?

Regardsing the base. What are your preferences: `base`, `baseObject`, else? I love everything short. You know. :smile:

**Comment by ericelliott** [comment]
## Complexity is reduced in this PR because we're fixing a violation of the open-closed principle. Extending the stamp API in the future will be awkward without this change.

* The implementation of the factory is only changed by two characters: (baseObject, ...args) becomes ({baseObject}, ...args) in the function signature.
* call site complexity is reduced for every call that omits a `baseObject` (which will be lots of calls).
* We add only a little extra typing for people who want to pass a baseObject: `myObj = myStamp({baseObject});`

**Comment by ericelliott** [comment]
I'm fine with `base`. I think it's descriptive enough in the context of the stamp.

**Comment by koresar** [comment]
You loooove bit fonts and attention. :)
I do agree with open-closed principle argument though.
Can we drop the `...args` now? I believe `options` will replace it completely. Otherwise people will do `myStamp(null, arg1, arg2)`, where `null` is the options object.

**Comment by ericelliott** [comment]
Remember, the args were initially added to stampit in order to support legacy constructors. We'll need to come up with an alternative support mechanism if we drop it (although I was never happy with the support we had, so I'm happy to address legacy constructors in a different thread).

**Comment by koresar** [comment]
We can reserve the `.arguments` property in the options. Right? :)

**Comment by koresar** [comment]
We were thinking of having the legacy constructors support via "general utility stamps". Like `convertConstructor` stamp. The usage could be:

```js
import convertConstructor from 'utility-stamps';
const NewConstructor = convertConctructor(OldConstructor);
let obj = NewConstructor({ arguments: [arg1, arg2] });
```

**Comment by ericelliott** [comment]
We could, but then call sites would be doing this:

```js
const myObj = promiseStamp({
  arguments: [(resolve, reject) => {
    // promise body
  })];
});
```
vs:
```js
const myObj = promiseStamp(null, (resolve, reject) => {
  // promise body
});
```

I don't like either of those. A better implementation would be:

```js
const myObj = promiseStamp({
  promise (resolve, reject) {
    // promise body
  };
});
```

But you'd have to create that as a custom stamp. then we lose the convenience of `convertConstructor()`.

Is there a better way we could implement `convertConstructor`?

**Comment by koresar** [comment]
I like the top one.
(btw, you must not compose promises with other things. Specs discourage that.)

There are dark ways to implement `converConstructor` by looking at function arity and other metadata, but this where the gates of hell will open. I don't want that.

Let's reserve `arguments` to KISS.

**Comment by ericelliott** [comment]
We still have the same problem that plagues the original `convertConstructor`: you can't safely compose constructors that take arguments. What if convertConstructor could map options?

```js
const promiseStamp = convertConstructor(Promise, {
  argument: 'promise' // look for argument on the `promise` option.
});
```

```
const myObj = promiseStamp({
  promise (resolve, reject) {
    // promise body
  };
});
```

We could be fancy and take `arguments` (for an array of args), or `argument` (for a single argument).

Yet another cool thing we could do with a proper `options` object...

Go ahead, [click that merge button](https://github.com/stampit-org/stamp-specification/pull/24).

**Comment by koresar** [comment]
Wow. Lovely idea! That's a killer feature!
*Until classic constructors collide properties/methods* :smile:

**Comment by koresar** [comment]
After some thought I think this `baseObject` change requires changes to the initializers.

### The `options` parameter of any stamp factory should be passed raw to the initializers.
* `baseObject` should be renamed to `instance`.
* Drop the `args` from the initializers arguments.
* Assign `stamp` proeprty to the options parameter for the initializers.

Code:
```js
// The options object have everything passed to the factory, plus "stamp" property
let stamp = compose({ initialize: ({ instance, stamp, myArg1 }) => console.log(myArg1) });

// Passes the "instance" object and an additional argument.
let obj = stamp({
  instance: { bla: 1, foo: 2 }, // this is kind of "defaults" proposed above
  myArg1: "hello world" // prints this text in the initializer
});
```

**Comment by koresar** [comment]
A better way probably have two arguments for factories, not just one.
```js
let stamp = compose({ initialize: ({instance, stamp, {myArg1}}) => console.log(myArg1) });
let obj = stamp(
  { bla: 1, foo: 2 }, // instance
  { myArg1: "hello world" } // additional options, not merged to instances
);
```

**Comment by ericelliott** [comment]
* `baseObject` should be renamed to `instance`: **Agreed.**
* Drop the args from the initializers arguments: **Agreed.**

As I read it, these would be the new proposed initializer args:

```js
{
  instance,
  stamp,
  options
}
```

Correct?

**Comment by koresar** [comment]
Implemented and merged. Cheers Eric!
