### ISSUE TITLE
The king of the kings - the `compose()` function

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#3]
A single `compose()` function should serve the following:
1) Create stamps from other composables.
```js
compose(composable1, composable2);
```

2) Create stamps from discriptors.
2.1) Descriptor is the argument(s) you pass to the `compose()`. Exactly like `stampit(arg)`. Example:
```js
compose({
  methods: ...
});
```
In the code above we are calling the `compose()` function with a single argument which is a descriptor object.

3) Can be attachmed to any object to make the object a composable.
```js
var anObject = {};
anObject.compose = compose;
```
In the code we are making a usual object a composable.

-----

How about that?

**Comment by ericelliott** [comment]
> 2.1) Descriptor is the argument(s) you pass to the compose(). Exactly like stampit(arg)

Yes, all stamps have descriptors, but not all descriptors need to be attached to stamps. In other words, a stamp is always a function that returns object instances which has descriptor properties  `stamp.compose.*`, but you can have a descriptor that is not a function, and is only good for passing into `compose()`. That means that `compose()` would be the default Stampit export.

In order for this to work:

```js
compose({
  methods: ...
});
```

Compose would have to first look for `stamp.compose` on the passed argument obj. If it does not exist, it could assume that the object is the descriptor which is normally attached to the `.compose` property.

**Comment by koresar** [comment]
Perfect! I love to know that we are on the same page. :)

**Comment by koresar** [comment]
The adventures of the `compose()` function continues in the issue #14
