### ISSUE TITLE
What's the point of stamp({instance}) ?

### ISSUE THREAD

**Issue by markokr** [stampit-org/stamp-specification#35]
There is minor issue that it uses the "magic-arg" antipattern.  As you have already discussed in #26.

But the major issue is that how this is supposed to be generally useful?  I assume you have some sort of use-case in mind, although I can't see it.  Current spec also does not descibe any details.

Main problem is that whatever use-case you have in mind, is it really possible to do it safely without specifying non-trivial amount of restrictions what user code is allowed to do with instance attributes? Restrictions for both init functions and rest of the code.

And even when it's possible to spec some behaviour that does not break everything it touches, how will you describe the resulting behaviour to user?

Unless you have really well thought out handling of various interactions that can happen, it seems better to just remove it from spec.

The natural flow I see in current spec is that the 'options' arg of stamp is exactly same object given to initializers, without any modifications and fully user-controlled properties.

**Comment by ericelliott** [comment]
> There is minor issue that it uses the "magic-arg" antipattern. As you have already discussed in #26.

I can't think of a better way to allow the end user to pass an instance to be modified into a stamp than to reserve a property of the options object. Can you?

> But the major issue is that how this is supposed to be generally useful?

Allowing an `instance` argument to be passed provides an official way to tell a stamp to extend an existing object -- a capability that has been requested by several Stampit users for various purposes. I believe its purpose is spelled out in the spec:

> Take an options object which may contain an .instance property. Return the mutated instance.

Do you have suggestions about how we could make the purpose more clear?

> Main problem is that whatever use-case you have in mind, is it really possible to do it safely without specifying non-trivial amount of restrictions what user code is allowed to do with instance attributes? 

The assumption is that there are no restrictions. User code (stamps) may mutate the instance in any way it wants to -- including complete replacement of the instance. We offer a large degree of freedom in this regard specifically because people may come up with use cases that we never envisioned -- and that's OK.

> The natural flow I see in current spec is that the 'options' arg of stamp is exactly same object given to initializers, without any modifications and fully user-controlled properties.

It is the same. What makes you think otherwise?

**Comment by markokr** [comment]
> >  There is minor issue that it uses the "magic-arg" antipattern. As you have already discussed in #26.
> 
> I can't think of a better way to allow the end user to pass an instance to be modified into a stamp than to reserve a property of the options object. Can you?

* Second argument, like you already did with initializers.
* Extra method on stamp, or under .compose.  [ stamp.mogrify(instance, options) ]

> > But the major issue is that how this is supposed to be generally useful?

> Allowing an instance argument to be passed provides an official way to tell a stamp to extend an existing object -- a capability that has been requested by several Stampit users for various purposes. I believe its purpose is spelled out in the spec:
>
>   **Take an options object which may contain an .instance property. Return the mutated instance.**
>
> Do you have suggestions about how we could make the purpose more clear?

Spell out what happens - "deepProperties are merged into whatever lives under instance, shallow props overwrite everything, initializers are run again, what happes with 'instance' property, \_\_proto\_\_ will be ???."

> > Main problem is that whatever use-case you have in mind, is it really possible to do it safely without specifying non-trivial amount of restrictions what user code is allowed to do with instance attributes?
>
> The assumption is that there are no restrictions. User code (stamps) may mutate the instance in any way it wants to -- including complete replacement of the instance. We offer a large degree of freedom in this regard specifically because people may come up with use cases that we never envisioned -- and that's OK.

So "whatever happens, happens"?

The whole problem with it is that after people redesign their app to .compose-based factory functions, they cannot immediately use .mogrify().  They need to do second redesign so that .mogrify() works sanely on their objects.

> > The natural flow I see in current spec is that the 'options' arg of stamp is exactly same object given to initializers, without any modifications and fully user-controlled properties.
>
> It is the same. What makes you think otherwise?

The "instance" magic arg, that everybody needs to know about and work around.  I cannot create stamp that simply installs all opts under instance or does JSON.stringify().

**Comment by troutowicz** [comment]
I have an example of why the `instance` property can be problematic for libraries trying to use the stamp spec. I'll update this post with it when I get a chance this morning.

**Comment by markokr** [comment]
Btw, I'm not saying it is not useful.  I'm saying it's useful only in small subset of cases where the usual composable instance factories are useful.  By putting hooks into main flow means the whole spec is designed to be useful only in that small subset of cases.

It does look like it should be part of some specific impementation, not spec.

Compare [Promises/A+](http://promisesaplus.com) spec to [ES6-Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) to full API of actual implementation, like [When](https://github.com/cujojs/when/blob/master/docs/api.md) or [Bluebird](https://github.com/petkaantonov/bluebird/blob/master/API.md).  Not all occasionally useful stuff is shuffled into spec.

**Comment by troutowicz** [comment]
So my example.

Consider [react-stamp](https://github.com/troutowicz/react-stamp). react-stamp depends on React's `Component` constructor function. This constructor function accepts [3 arguments](https://github.com/facebook/react/blob/master/src/isomorphic/modern/class/ReactComponent.js#L23). The current stamp spec reserves the first stamp argument for the `options` object.

Despite being able to create a new initializer signature during stamp creation. (like I do [here](https://github.com/troutowicz/react-stamp/blob/master/src/utils/descriptor.js#L38)), React (not the developer) handles the passing of arguments to the Component (stamp) when creating a  new `ReactElement` (stamp instance). React does not know to parse its arguments out the first passed argument like the stamp spec specifies. So react-stamp has to break the spec to [work](https://github.com/troutowicz/react-stamp/blob/master/src/index.js#L30).

**Comment by ericelliott** [comment]
> Second argument, like you already did with initializers.

That would dictate the stamp method signature even more. We've had this conversation already, [in issue 26](https://github.com/stampit-org/stamp-specification/issues/26).

> Extra method on stamp, or under .compose. [ stamp.mogrify(instance, options) ]

That would make things more complicated, not less complicated.

> Spell out what happens - "deepProperties are merged into whatever lives under instance, shallow props overwrite everything, initializers are run again, what happes with 'instance' property, __proto__ will be ???."

Don't we already spell that out in the [Priority Rules section](https://github.com/stampit-org/stamp-specification#priority-rules)? Initializers don't get run twice. The instance stamp option is the object being mutated by the stamps.

[Prototype handling is spelled out, too](https://github.com/stampit-org/stamp-specification#stamp):

> If present, the existing prototype of the instance must not be mutated. Instead, the behavior (methods) must be added to a new delegate prototype.

Moving on...

> It is unsafe to pass object that may have 'instance' to stamp.

Ah, this I do understand. Yes, `instance` is a reserved key, but in Stampit, the whole first argument had a special meaning, and it still turned out to be an extremely useful tool. We couldn't do literally anything we wanted with stamps, but we could do a whole lot with them.

Can you come up with an alternative mechanism to extend existing objects? You mentioned a special method. How do you envision that would work? Illustrative code would be useful.

There is a [reference implementation](https://github.com/stampit-org/stamp-specification/tree/ericelliott-simplify-example) you can refer to.

**Comment by ericelliott** [comment]
> Consider react-stamp. react-stamp depends on React's Component constructor function. This constructor function accepts 3 arguments. The current stamp spec reserves the first stamp argument for the options object.

I still don't understand why it matters that React.Component takes different args. Your stamp has its own function signature, and you can literally pass anything you want to  the React.Component constructor, can't you?

**Comment by troutowicz** [comment]
I must be missing something...

```js
const MyComp = createStamp(React, {
  render() {}
}
```

There are two ways that I am aware of to instantiate a React component.

`<MyComp />`
OR
`React.createElement(MyComp);`

Neither of those allow me to explicitly pass arguments to the factory function.

Your current stamp function signature expects the first argument to be the `options` object. See [here](https://github.com/stampit-org/stamp-specification/pull/18/files#diff-1b3ef822ec87668673adf6a07c81d02cR48). React knows nothing about the stamp spec, it will pass [3 arguments](https://github.com/facebook/react/blob/master/src/isomorphic/modern/class/ReactComponent.js#L23). The arguments will not be properties of your `options` object.

**Comment by koresar** [comment]
I read this thread (finally).
Tim made me think about this very hard:
```js
function ReactComponent(props, context, updater) {
```

@ericelliott I'd rather add the following to the specs:
> The specs implementations are allowed and encouraged to extend the standard with anything compatible. For example:
>> stamp(options, [arg1], [arg2], ...) -> translates to initializers like so
```js
init(({ args }) => { console.log(args[1], args[2], ...); });
```

Basically, I propose to allow people to extend the specs with their own neat things but ensure they do not break interoperability with other implementations.

**Comment by koresar** [comment]
> I can't think of a better way to allow the end user to pass an instance to be modified into a stamp than to reserve a property of the options object. Can you?

What about that?
```js
instance = stamp.call(instance, options);
```
5 more characters only.

**Comment by markokr** [comment]
@koresar: stamp may live under object, so you cannot simply pass instance as this.  Hm, actually you can, if you change stamp signature to always use `new`.  So:

* new stamp(...) => new instance
* stamp.call(instance, ...) => modify

But it does not seem like good idea as the modify operation is different enough from initial setup.

@ericelliott: if you agree that initalizers should not be run during modify - which is really sensible idea - then there is no point of passing any other arguments in options, yes?  As nothing will use them. So currently you have 2 different operations going through same function:

* stamp({...initializer-options...}) -> new object
* stamp({instance: xx}) -> edit object

This shows even more clearly that they should not operate via same function call. My suggestion:

* stamp.modify(instance)

**Comment by koresar** [comment]
>  stamp may live under object

So what? Stamp internals are hidden from users.

**Comment by markokr** [comment]
My point was that 'this' will be set.

**Comment by koresar** [comment]
> My suggestion:
* stamp.modify(instance)

It won't be a "composable" anymore, but "modifyable".

**Comment by koresar** [comment]
> My point was that 'this' will be set.

True. I missed that.

**Comment by markokr** [comment]
"modifyable" - yeah, if you make clear that this is different class of stamp, then it's fine.

That's my issue with it - if "composable" is equal to "modifiable" it raises the complexity of the "composeable" concept, and thus lowers the worth.

**Comment by koresar** [comment]
Yes, indeed @markokr. We are not introducing any new ".modify()" or ".whatever()" to the specs. That's 100%.

Any other ideas/proposal?

**Comment by markokr** [comment]
Drop it from spec, publish extra module that does the object in-place edit as sort-of companion to base modules.  I don't think it needs additional spec, what the edit can/must do should fall out from main composables spec.

**Comment by koresar** [comment]
Agree @markokr :+1: 
;) https://github.com/stampit-org/stamp-specification/issues/35#issuecomment-144251661

**Comment by ericelliott** [comment]
> `init((options, { args }) => { console.log(args[1], args[2], ...); });`

As we've discussed in-depth in the Stampit threads, taking arbitrary args is an anti-pattern for composables, because it opens up a large probability that composables will be incompatible with each other because they expect different arguments.  Believe me, that's a much bigger can of worms than a single reserved property on an options object.

**Comment by ericelliott** [comment]
> I must be missing something...

I think you're saying that there is some arbitrary relationship between the arguments somebody passes into the stamp and the arguments you must use to create a component. I don't see the problem, so either you're missing something, or I'm missing something.

What's wrong with this signature?:

```js
const MyComponent = reactStamp({
  React,
  render () { return (<div></div>); }
});

React.render(<MyComponent />);
```

**Comment by ericelliott** [comment]
Since any initializer can replace the instance, we can move instance handling into a utility stamp and have zero reserved properties on the stamp options argument. We could even go further and make the options argument itself a "best practice" instead of baked into the spec. In other words:

* No rules about stamp parameters.
* Want to augment an instance? Do it with the first stamp you pass to compose.
* New initializer signature: `({ instance, stamp, arguments }) => instance`

**Comment by troutowicz** [comment]
```js
import createStamp from 'react-stamp';
import React from 'react';

// stubbing React.Component
function Component(props, context) {
  console.log(props);
  this.props = props;
  this.context = context;
}

Component.prototype.setState = function() {};
Component.prototype.forceUpdate = function() {};

const Comp = createStamp({ Component }, {
  render() {
    return null;
  }
});

React.renderToStaticMarkup(<Comp foo={true}/>);
```

Using the current proposed stamp signature, what do you think will be logged?

What should be logged is `{ foo: true }`.

**Comment by ericelliott** [comment]
```js
const Comp = createStamp({ Component }, {
  render() {
    return null;
  }
});
```

This is not the current proposed stamp signature (currently in the Readme). This is:

```js
const Comp = createStamp({
  Component,
  render() {
    return null;
  }
});
```

And without seeing the stamp implementation, I can't tell you what will be logged. How is `Component` used inside `createStamp`? That (not the stamp function signature) is what will determine what gets logged, if anything. Show me the implementation of the stamp, and then I'll have something intelligent to say about what (if anything) gets logged.

**Comment by troutowicz** [comment]
OK. react-stamp's `createStamp` method signature is unique to react-stamp. It should not be compared to your example implementation. Also, `createStamp` is not the stamp factory function, it is the factory that returns the stamp factory function. The signature of `createStamp` is not and should not be part of the spec.

I'm sorry, I thought you were aware that this implementation of react-stamp is available [here](https://github.com/troutowicz/react-stamp).

I have also updated react-stamp to use your proposed spec update in PR #38. Making the `options` argument **recommended** and not **required** fixes all of the problems I had. :)

**Comment by markokr** [comment]
Please don't promote existing object edit in spec.  Remeber the shallow/deep discussion we had?  It will be triple complex for edit case.

**Comment by markokr** [comment]
Last point about edit - if want to have any chance of robust edit, there needs to be a way to get stamp descriptor from instance.  Normal way for that is `.constructor`.  If you don't have such way, any edit will be fragile as it can corrupt shared state.

**Comment by ericelliott** [comment]
I don't see an obvious link between having access to the stamp from the instance and fragile edits. Can you explain with some code?

**Comment by markokr** [comment]
Deep properties from one stamp must not merge into shallow props from other stamp.
```
var s1 = compose({properties: { attr: window });
var s2 = compose({deepProperties: { attr: { foo: {}} });
var o = s2.edit(s1());
```

**Comment by ericelliott** [comment]
They already don't, per the existing spec:

> Different descriptor properties, one or more stamps:
>* Instance properties have lowest priority
>* Shallow properties override deep properties
>* Descriptors override everything

I still see no connection to the `.constructor` prototype property.

**Comment by ericelliott** [comment]
> Deep properties from one stamp must not merge into shallow props from other stamp.

They already don't, per the existing spec:

> Different descriptor properties, one or more stamps:
>* Instance properties have lowest priority
>* Shallow properties override deep properties
>* Descriptors override everything

I still see no connection to the `.constructor` prototype property.

**Comment by markokr** [comment]
How do you know if existing instance attribute is deep or shallow?

**Comment by ericelliott** [comment]
Stamps use a single stamp descriptor which is composed from source descriptors. That descriptor has different properties for deep vs shallow.

**Comment by markokr** [comment]
Indeed.  But we are operating on instance here, this is a object where everything is put together.

**Comment by ericelliott** [comment]
Stamp composition is done at `compose()` time, not instantiation time. During instance creation, everything is already put together, so your concern is not an issue.

**Comment by markokr** [comment]
Um, I was talking about edit, aka. the removed `stamp({instance: someObj})` behaviour.

If you want to still allow it as extension / external module, the spec should make stamp descriptor somehow available under instance.

I don't particularly care about it, and if nobody else does then we can forget it.

**Comment by ericelliott** [comment]
> Um, I was talking about edit, aka. the removed stamp({instance: someObj}) behaviour.

I see.

1. `instance` had the lowest priority in the spec, which means we ignored its stamp altogether and just treated its properties as defaults that anything could override.
2. That seems like [a separate issue](https://github.com/stampit-org/stamp-specification/issues/39) to me.

**Comment by markokr** [comment]
Yes, this issue is done now.

**Comment by ericelliott** [comment]
Great. We'll close it as soon as [the outstanding PR gets merged](https://github.com/stampit-org/stamp-specification/pull/18).

**Comment by koresar** [comment]
The PR got merged.
