### ISSUE TITLE
Initialiser instance replacement conditions

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#45]
I want my stamp to return `null` in some cases:
```js
const stamp = compose({ initializers: [({ condition }) => {
  if (!condition) {
    return null;
  }
}]});

let myObject = stamp({ condition: false }) || otherLogicGoesHere();
```

Current specs say: 
> If the initializer returns a different object, it replaces the instance.

And I think this is correct. I consider `NaN`, `0`, `''` and `null` objects. We should be more clear on that:
> If the initializer **does not** return `undefined`, the returned value replaces the instance.

Agree?

**Comment by troutowicz** [comment]
`NaN` is a static property of the `Number` primitive, and `null` is a primitive without an object equivalent.

But I don't see an issue with your proposed change.

**Comment by ericelliott** [comment]
`typeof null === object`

**Comment by troutowicz** [comment]
/me sighs

> Except for null and undefined, all primitive values have object equivalents that wrap around the primitive values ([source](https://developer.mozilla.org/en-US/docs/Glossary/Primitive))

I guess I am interpreting that wrong. But `typeof undefined === 'object`` is false. \o/

**Comment by ericelliott** [comment]
This complicates things a little bit.

```
const stamp = compose({ initializers: [({ condition }) => {
  if (!condition) {
    return null;
  }
}]});
```
If we let that work, it complicates things a bit more than you think. Could you throw and use `try/catch` instead, or return a rejecting promise, or ... well... anything else?

If users of stampit have to guard against stamps that may or may not return a stamp... I can see that causing some bugs and confusion.

**Comment by koresar** [comment]
We can accept objects only as properly stamped objects.
> If the initializer returns object (as in `_.isObject(obj)`) the returned value replaces the instance.

So that only objects are assumed as instances.

https://github.com/stampit-org/stamp-specification/blob/master/examples/compose.js#L26
will become:
```js
      const returnValue = initializer.call(obj, options,
        { instance: obj, stamp: Stamp });
      if ( isObject(returnValue) ) {
        obj = returnValue;
      }
```

How about that?

**Comment by ericelliott** [comment]
:+1:

**Comment by koresar** [comment]
This was a wrong implementation.

> If the initializer returns a different object, it replaces the instance.

The object can be: any primitive object, or POJO, or function. I.e. the only value we should check against is the `undefined`.

```js
      const returnValue = initializer.call(obj, options,
        { instance: obj, stamp: Stamp });
      if ( isUndefined(returnValue) ) {
        obj = returnValue;
      }
```

A PR is welcome. Tests should be added/changed accordingly.

**Comment by koresar** [comment]
The specs should be changed. Two more words needed.
> If the initializer returns a different object **except undefined**, it replaces the instance.
