### ISSUE TITLE
Reference impl. is missing args feature

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#46]
This feature:
https://github.com/stampit-org/stamp-specification#initializer-parameters
should have been implemented here:
https://github.com/stampit-org/stamp-specification/blob/master/examples/compose.js#L27

**Comment by troutowicz** [comment]
Yep. :)

**Comment by ericelliott** [comment]
This is why I wanted more eyes on the code. =)

I always overlook things the first time.

**Comment by koresar** [comment]
Done.
