### ISSUE TITLE
Double initializer behaviour

### ISSUE THREAD

**Issue by markokr** [stampit-org/stamp-specification#52]
I think the spec should clarify what happens when same initializer comes from different stamps:

1) Initializer will be run several times.
2) Double initializer will be removed during compose (based on === equality).

Looks like 1) is what happens now.  Users need to be aware about it if this behaviour stays.

But seems 2) might be more useful for users - they don't need to explicitly guard against multiple executions.

**Comment by ericelliott** [comment]
This is not a problem in practice, and the question has only come up once during the entire lifetime of stamps.

**Comment by markokr** [comment]
So by spec the behaviour is undefined?  This means implementation can do either 1) or 2) ?

**Comment by ericelliott** [comment]
No. It is defined, and it does 1.

**Comment by ericelliott** [comment]
See [this issue](https://github.com/stampit-org/stampit/issues/177) for discussion.
