### ISSUE TITLE
Replace "deepProps" with composable utility stamp

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#58]
Looking at the usage of the "deepProps", and at the complexity it adds to both the standard **and** the implementation, I would propose to ditch the "deepProps" and "deepStaticProps". Replace it with a utility stamp(s) (aka composable behaviour(s)).

Thoughts?

**Comment by ericelliott** [comment]
These are pretty core features. I'd need a lot more detail on the proposed utility stamps and their usage compared to the built-in functionality.

**Comment by koresar** [comment]
Current usage of the "deepProps":
```js
const SomeStamp = ...;
const Stamp = SomeStamp.compose({ deepProperties: { a: { b: 1 } } });
// The line above deep merges `a` to the `.compose.deepProperties`. But then...
// the additional deep merging happens when an object is instantiated.
const obj = Stamp();
```

Proposed utility stamp:
```js
const SomeStamp = ...;
const Stamp = SomeStamp.compose(DeepProps).deepProperties({ a: { b: 1 } });
// The line above will deep merge given object(s) to the `.compose.properties`.
// No additional deep merging in the next line.
const obj = Stamp();
```

The implementation of the `DeepProps` is rather simple:
```js
export default compose({ staticProperties: { deepProperties(...args) {
  _.merge(this.compose.properties, ...args);
  return this;
}}});
```

**Comment by ericelliott** [comment]
> additional deep merging happens when an object is instantiated.

Can you explain this in more detail?

**Comment by koresar** [comment]
@ericelliott do you remember the time we introduced the deep properties to the stampit? There was a short debate on which is more priority - references or deep properties. We came to the conclusion that references is more important. It was right decision, but we better to leave it to user's discretion. 

The proposed change gives a composables user the right to choose when and how he want the things merged.
```js
DeepProps.properties({ a: 1 }).deepProperties({ a: { deep: 1 } });
// or
DeepProps.deepProperties({ a: { deep: 1 } }).properties({ a: 1 });
```

**Comment by ericelliott** [comment]
Couldn't we enable such mixin utilities to work without changing the default specification and behavior?

Why is it preferable to eliminate the concept of deep props from the spec entirely?

**Comment by koresar** [comment]
> Can you explain this in more detail?

Sure.
Deep merging is CPU intense operation. We can move it to the [stamp composition step](https://github.com/stampit-org/stamp-specification/blob/master/examples/compose.js#L63) instead of [object instantiation step](https://github.com/stampit-org/stamp-specification/blob/master/examples/compose.js#L23).

**Comment by koresar** [comment]
> Why is it preferable to eliminate the concept of deep props from the spec entirely?

Four reasons:
1) Simpler "stamp" concept. Simpler implementation.
2) The feature is barely used. (I'm the only using it. Haven't heard heard of anyone else all this time.)
3) No debates on what is more priority - props or deep props.
4) More CPU friendly.

**Comment by ericelliott** [comment]
> 1) Simpler "stamp" concept. Simpler implementation.

Why do we care? Shouldn't most users be using stampit, or the stamp utils to create custom implementations?

> 2) The feature is barely used. (I'm the only using it. Haven't heard heard of anyone else all this time.)

I use deep props exclusively for all composable stamp state, and I recommend the same to everybody else using stamps.
 
> 3) No debates on what is more priority - props or deep props.

The spec ended those debates already, and anybody who disagrees can sidestep the default behavior with a utility stamp.

> 4) More CPU friendly.

How about we conditionally merge only if there's something to merge? Is than an acceptable perf compromise? =)

**Comment by ericelliott** [comment]
Don't forget, this idea comes at a usability cost:

```js
import deepProps from 'stamp-utils/deep-props'; // need to import another util, now.

// Now there's a static method stuck to any stamp you compose this with, removing
// the almost complete control of the stamp static API:
const Stamp = SomeStamp.compose(DeepProps).deepProperties({ a: { b: 1 } }); 
```

vs...

```js
// No additional import. No stamp static API changes required:
const Stamp = SomeStamp.compose({ deepProperties: { a: { b: 1 } } });
```

I think a change like this requires a compelling use case, and if you're really concerned about perf, some compelling perf difference tests.

**Comment by koresar** [comment]
I'm not concerned about perf at all. :) It's just one of the benefits. The least important one.

1)
> Don't forget, this idea comes at a usability cost

The answer to that is your statement above:
> Why do we care? Shouldn't most users be using stampit, or the stamp utils to create custom implementations?

2)
So, now I know there are only two people using deep properties. Are you using deepStaticProperties? I have never used it yet.

3)
> sidestep the default behavior with a utility stamp.

I can't imagine the implementation. What do you mean by that?

4)
> How about we conditionally merge only if there's something to merge?

This is how it already works in stampit v2.

**Comment by ericelliott** [comment]
> EE: Don't forget, this idea comes at a usability cost

> K: The answer to that is your statement above:

> EE: Why do we care? Shouldn't most users be using stampit, or the stamp utils to create custom implementations?

I don't see how these are related. My "why do we care?" question refers to people using an existing stamp spec implementation rather than rolling their own and being exposed to the complexity of the stamp spec itself.

The usability cost and API awkwardness I'm referring to applies to the stamp's end users.

In other words, it doesn't matter so much if stamp spec implementation has some complexity, because end users are shielded from it. It does matter that the stamp API is highly usable, because end users will be using those APIs directly.

**Comment by ericelliott** [comment]
> 2) So, now I know there are only two people using deep properties.

No, you don't know that. Have you done a thorough search of all the publicly available projects using stamps? Have you even informally surveyed stamp users?

Frankly, I don't think stamps even have enough users to come to statistically significant observations about which features are most important to our users. This looks very much like jumping to unsupported conclusions to me, and I really don't think a standard specification body should make decisions this way.


> EE: sidestep the default behavior with a utility stamp.

> K: What do you mean by that?

Wouldn't your example, or virtually any other implementation work *with the existing spec?*

```js
export default compose({ staticProperties: { deepProperties(...args) {
  _.merge(this.compose.properties, ...args);
  return this;
}}});
```

> How about we conditionally merge only if there's something to merge?
> This is how it already works in stampit v2.

Good. Sounds like there's no real perf problem with the existing spec, then, correct?

**Comment by koresar** [comment]
Still, I'm very concerned about people not using the deep props (yeah, it could be only two of us). Wee need some usage statistics on it.

Would you agree that a barely used feature should not be part of a system?

**Comment by koresar** [comment]
> Good. Sounds like there's no real perf problem with the existing spec, then, correct?

It is still there unfortunately. The exactly same deep merging is happening over and over again per each new object. This could be avoided by shifting the deep merging step to happen only once - to the composition step.

**Comment by ericelliott** [comment]
> Still, I'm very concerned about people not using the deep props (yeah, it could be only two of us). Wee need some usage statistics on it.

Lacking data (which I mentioned we can't even collect statistically relevant data on without a much bigger stamp user base), this concern is basically a dream. You're concerned about a problem which may not exist at all.

Recruit about 10k more users, find me the relevant data, and **then** we'll discuss whether or not it's a problem.

**Comment by koresar** [comment]
Yeah. Agree.

**Comment by ericelliott** [comment]
> It is still there unfortunately. The exactly same deep merging is happening over and over again per each new object. This could be avoided by shifting the deep merging step to happen only once - to the composition step.

Can it be avoided without changing the composables spec?

**Comment by koresar** [comment]
You know what, I am wrong about the perf and the "happen only once" thing. :) Please, disregard.

I think this issue can be closed and opened/created again when we have some more statistics.

Thanks for the chat Eric.
