### ISSUE TITLE
Terminology proposal

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#59]
Stampit and this stamp-specification are somewhat different in terminology used. I propose to unify the wording.

* **Composable Descriptor** (aka **Descriptor**) is a meta data object which contains the information necessary to create an object instance. _(copy&pasted from the README)_
* **Composable** is an object which has property `.compose` which is a **Composable Descriptor**.
* **Stamp** - is both factory function *and* a **Composable**.

Thus, the following checks are becoming clear:
```js
const isDescriptor = obj => _.isObject(obj);
const isStamp = obj => _.isFunction(obj) && _.isFunction(obj.compose) && isDescriptor(obj.compose);
const isComposable = obj => isDescriptor(obj) || isStamp(obj);
```

Is logic present here?

UPD: Updated the code above in accordance to the discussion below and the latest README.md.

**Comment by ericelliott** [comment]
> `function isComposable(obj) { return _.isObject(obj) && isDescriptor(obj.compose); }`

That looks incomplete.

> Composables may also be POJO (Plain Old JavaScript Object) descriptors

From [the example](https://github.com/stampit-org/stamp-specification/blob/master/examples/compose.js#L8):

```js
const descriptor = composable.compose || composable;
```

See the stamp-utils for examples:

* [is-composable](https://github.com/stampit-org/stamp-utils/blob/master/source/is-composable/index.js)
* [is-descriptor](https://github.com/stampit-org/stamp-utils/blob/master/source/is-descriptor/index.js)
* [is-stamp](https://github.com/stampit-org/stamp-utils/blob/master/source/is-stamp/index.js)

**Comment by ericelliott** [comment]
IMO, it's important for the usability of `compose()` that we allow POJO descriptors which can look like this:

```js
{ methods }
```

Instead of this:

```js
{
  compose: {
    methods
  }
}
```

**Comment by koresar** [comment]
Can you explain what is Stamp?
From the `is-stamp` source code it is not clear that stamp is a Composable too. Or stamps are not composables???
I'm confused.

**Comment by ericelliott** [comment]
* A Stamp is a composable factory function.
* A Composable is an object that can be composed with stamps. A composable may be a stamp or a POJO descriptor.

**Comment by koresar** [comment]
> A Stamp is a composable factory function.

Should we say then "Stamp is a factory function and a Composable same time." ?

**Comment by koresar** [comment]
> A Composable is an object that can be composed with stamps. A composable may be a stamp or a POJO descriptor.

Or should we state the following: "A Composable is an object that can be composed with stamps **or other composables**. A composable may be a stamp or a POJO descriptor." ?

**Comment by ericelliott** [comment]
See updated PR for clarifications.

**Comment by koresar** [comment]
Okay. We got to some kind of consensus in the PR comments. As the result this function need to be changed:
https://github.com/stampit-org/stamp-utils/blob/master/source/is-stamp/index.js
Instead of
```js
const isStamp = (obj) => {
  return typeof obj === 'function' &&
    typeof obj.compose === 'function';
};
```
it should be this:
```js
const isStamp = (obj) => {
  return typeof obj === 'function' &&
    typeof obj.compose === 'function' &&
    isDescriptor(obj.compose);
};
```
@ericelliott do you agree?

**Comment by koresar** [comment]
Can I get write access to the https://github.com/stampit-org/stamp-utils/ please? I wanted to quickly submit a PR but don't want to start the forking procedure. :)

**Comment by ericelliott** [comment]
> it should be this:

No, because in the POJO descriptor requires at least one descriptor prop (otherwise, it would be useless), whereas the stamp descriptor may be empty. The current logic is correct.

**Comment by koresar** [comment]
The specs. does not say that at least one of the descriptor properties must be present.

Consider this:
```js
isStamp(compose());
```
Obviously, all the descriptor props could be missing.

I think this is a wrong implementation: https://github.com/stampit-org/stamp-utils/blob/master/source/is-descriptor/index.js

**Comment by ericelliott** [comment]
1. `isStamp(compose());` is currently fine. With an additional `isDescriptor();` test, it would break.
2. `isDescriptor()` would be pretty useless if there was nothing at all to base a positive test on. Unless you're suggesting that *any* object should pass the `isDescriptor()` test?

**Comment by koresar** [comment]
2. Yes. Any object should pass the `isDescriptor` test.
Otherwise this might not work on some implementations: `isDescriptor(compose().compose)`.

**Comment by koresar** [comment]
I've just updated the code in the first message. Now it implements the README.md exactly.

**Comment by ericelliott** [comment]
Ok.
