### ISSUE TITLE
propertyDescriptors new name?

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#6]
I'm looking for a better name for the [propertyDescriptors](https://github.com/stampit-org/stamp-specification#the-stamp-descriptor).

First of all we don't really want people to use this feature directly. `assign` and `merge` are more than enough in 99.9% cases.
Although, a `convertClass` (aka `convertConstructor`) would need `propertyDescriptors` to implement various scenarios, like [getters and setters](http://www.2ality.com/2015/02/es6-classes-final.html).
However, this might lead to unpredictable undesirable dehaviors (see node.js `url` object numerous problems). Also, it complicates the standard very much.

Thus, I see three options:
* Leave `propertyDescriptors` name as is.
* Rename to `props`.
* Drop the `propertyDescriptors` altogether.

Dunno which way is better. There are 3 Cons to have this. And only one Pro.

Any proposals?

**Comment by JosephClay** [comment]
@koresar Can you link to the node.js url problems for context?

**Comment by ericelliott** [comment]
> Rename to props.

No. That sounds like it's just describing key/value pairs like assign and merge.

> Drop the propertyDescriptors altogether.

Absolutely not. We need to give people full control over object behavior, including getters, setters, and enumerable values. We are not getting rid of the assign and merge shortcuts, so the 99% case is covered.. but we still need to support the 1% cases. I think it's probably more like 90% and 10%. People use getters very frequently, and right now, stampit has no support for them at all.

**Comment by koresar** [comment]
Still, I'm looking for a shorter name for `propertyDescriptors`.

1) Rename `propertyDescriptors` to something shorter
2) Leave `propertyDescriptors` long named on purpose.

BTW, consider the word "definition" as in `Object.defineProperty`.

**Comment by ericelliott** [comment]
We leave it because we're [optimizing descriptor names for consistency and clarity](https://github.com/stampit-org/stamp-specification/issues/9#issuecomment-123144743), not conciseness.

**Comment by koresar** [comment]
That's what I was asking for. Please, avoid closing issues while at least someone is discussing things.
