### ISSUE TITLE
Hook up property descriptors first for live getters/setters?

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/stamp-specification#61]
See https://github.com/stampit-org/stampit/issues/195#issuecomment-174165402

**Comment by ericelliott** [comment]
This may or may not be desirable for all use cases. Should we add an option to make this explicit?

**Comment by koresar** [comment]
Aren't they hook up first already? See [this LOC](https://github.com/stampit-org/stamp-specification/blob/master/examples/compose.js#L26).

**Comment by ericelliott** [comment]
Depends on what you mean by first. See [this LOC](https://github.com/stampit-org/stamp-specification/blob/master/examples/compose.js#L23).

**Comment by koresar** [comment]
This person's case is rathe unique. I doubt many people are going have same issue.

There are too many cases out there people might need. Let's avoid chasing everything.

I'd close this issue.

**Comment by ericelliott** [comment]
Perhaps. Let's see if anybody else asks for it, and address it then.
