### ISSUE TITLE
Consistent Static Descriptor Property Naming 

### ISSUE THREAD

**Issue by unstoppablecarl** [stampit-org/stamp-specification#68]
# Consistent Descriptor Property Naming Proposal

Change names of descriptors to be more consistent. 

## Reasoning

The current 'Instance` and 'Static' descriptor names are inconsistent. Descriptor names should be made up of words ordered by importance (as much as possible) that describe it. This ordering should be consistent across all descriptor names. 

## Proposal

1. For completeness all current and future 'Instance' descriptors will have an equivalent 'Static' descriptor with identical composition behavior used to compose properties onto the stamp object.

2. Static descriptors will be named by prefixing 'static' to the equivalent 'Instance' descriptor name.

### Changes To Current Descriptors

change `deepProperties` to `propertiesDeep`
change `deepStaticProperties` to `staticPropertiesDeep`

#### Core
- methods
- initializers
- configuration

#### Instance
- properties
- propertiesDeep
- propertyDescriptors

#### Static
 - staticProperties
 - staticPropertiesDeep
 - staticPropertyDescriptors

**Comment by ericelliott** [comment]
While I agree with the general principle of consistency, it's important to understand what is important to be consistent with. In the English language (which is at least understood and spoken in many countries around the world, and is used as a basis for naming things in virtual all software everywhere) adjectives come before subjects.

That's what we're remaining consistent with, e.g.:

`properties` (instance is default, so no reason to call it out)
`staticProperties`,
`deepStaticProperties`

etc...

**Comment by koresar** [comment]
Agree with Eric. Readability should be higher priority.

**Comment by unstoppablecarl** [comment]
I found myself unable to remember the order of the words and having to look them up constantly. Maybe it is just me.

**Comment by unstoppablecarl** [comment]
in the case of `deepStaticProperties` would it be reasonable to at least keep the adjective importance order consistent? `static` is a higher level grouping descriptor than `deep` and they are grammatically correct in any order. 

Would you be open to the `static` prefix convention? I would be able to remember the names then.

# Proposal v2

change `deepStaticProperties` to `staticPropertiesDeep`

 - properties
 - deepProperties
 - propertyDescriptors

 - staticProperties
 - staticDeepProperties
 - staticPropertyDescriptors

**Comment by koresar** [comment]
That sounds both logical and English readable to me. 

Hey @ericelliott I knowledge it's a breaking change although this makes a lot of sense. Let's do it?

**Comment by unstoppablecarl** [comment]
How will it break anything I thought the spec is still being finalized?

**Comment by koresar** [comment]
It won't break anything in production. That's true. :) Sorry for not pointing that out.

**Comment by unstoppablecarl** [comment]
@ericelliott thoughts?
