### ISSUE TITLE
`assign` implementation

### ISSUE THREAD

**Issue by JosephClay** [stampit-org/stamp-specification#7]
Currently, ES5 getters and setters aren't usable in the spec due to [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) being defined to merge objects literals instead of [`Object.defineProperties`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties). ES6 exacerbates this problem because it makes using getters and setters so much easier with object literal shorthand.

@koresar hit on the subject of getters and setters being a problem via `convertConstructor` with ES6 classes in #6. However, I think the problem is larger and not restrained to ES6 classes. I run into the problem when converting a standard encapsulation to `stampit` e.g.
```js
// before
let point = function({ x, y }) {
    return {
        get len() {
            return Math.sqrt(x * x + y * y);
        }
    };
};

// after
let point = stampit()
    .init(function() {
        let x, y;
        return stampit.assign(this, {
            coords(newX, newY) {
                x= newX;
                y= newY;
                return this;
            },
            get len() {
                return Math.sqrt(x * x + y * y);
            }
        });
    });

// Uncaught TypeError: Cannot read property 'len' of undefined
point().coords(2, 2).len
```

My thoughts are that we need to be able to handle this in both `methods` and `stampit.assign` and define `assign` in the spec as using `Object.defineProperties`.

**Comment by ericelliott** [comment]
This is addressed with `.propertyDescriptors`, which supports `Object.defineProperties()` property descriptors.

**Comment by JosephClay** [comment]
Cool :+1:

**Comment by koresar** [comment]
A side note: The `stamp.compose.propertyDescriptors` object will be deep merged when composing stamps.
