### ISSUE TITLE
It's time to start version the specs

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#76]
This repository requires versioning using SemVer.

Proposal. Start with 0.1. As soon as we feel ready we publish the v1.

I'll do that tomorrow in case of absence of a discussion. :)

**Comment by troutowicz** [comment]
v0.1 sounds good to me.

**Comment by ericelliott** [comment]
There are now several implementations of the stamp spec. Maybe it's best to start at 1.0? =)

**Comment by troutowicz** [comment]
Something I'd like to see before v1.0 is the ability to import the specs test suite into a spec related projects. Right now I'm using a copied version for `react-stamp`. If I recall right the only change I required was a different `compose` import path in each test file.

**Comment by koresar** [comment]
> There are now several implementations of the stamp spec. Maybe it's best to start at 1.0? =)

Good point. True.

> Something I'd like to see before v1.0 is the ability to import the spec's test suite into a spec related project.

Will do! See https://github.com/stampit-org/stamp-specification/issues/78

**Comment by ericelliott** [comment]
We already have (at least) 3 libs working against the stamp spec. It should have been 1.0 back in October.

New features will just bump the version accordingly.

**Comment by koresar** [comment]
Right. Then it will be v2.0.

**Comment by JosephClay** [comment]
:clap: 

We should make a note in the stampit v3 README that stampit v3 uses the stamp v2 spec to avoid confusion.

**Comment by koresar** [comment]
Just browsed though http://semver.org/
The list of its previous versions is: `v2.0.0-rc.2 v2.0.0-rc.1 v1.0.0 v1.0.0-beta`

I believe it's safe to declare the upcoming specs release as `v1`, and the previous as `v1.0.0-rc.1`.

**Comment by ericelliott** [comment]
:+1:

**Comment by koresar** [comment]
Huh. It appears the specs version were `1.0.0-beta` since July 2015. :)
https://github.com/stampit-org/stamp-specification/commit/8898663b497b6512b6a2a730d6729bed511fde0d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R3

**Comment by ericelliott** [comment]
Good. =)

**Comment by koresar** [comment]
Any objections to name the current specs in "master" branch as Version 1?

My personal view is the specs are finally full, flexible, hackable, and beautiful in general. :angel:

**Comment by troutowicz** [comment]
v1 sounds good now.

**Comment by JosephClay** [comment]
:+1: They are beautiful

**Comment by koresar** [comment]
stamp-specification v1 NPM module was published. https://www.npmjs.com/package/stamp-specification
