### ISSUE TITLE
deepConfiguration and configuration

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#77]
So, yesterday I got the case when I needed an object in `.configuration` to be completely replaced (not merged!).

```js
const ReactRef = compose({configuration: {React: window.React || global.React}});
const MyComponent = ReactRef.compose(bla bla bla);

//... later on in another file ...
import React from 'react';
const MyFinalComponent = MyComponent.compose({configuration: {React: React}}).compose(other stuff);
```
I don't want the `React` to be deeply merged because they can be different instances/versions.

Proposal: have `deepConfiguration` which would be deeply merged. And `configuration` for assigning.

**Comment by ericelliott** [comment]
I'm not opposed.

**Comment by koresar** [comment]
Great! Feel free to merge #79 right now :)

**Comment by koresar** [comment]
![partyparrot](https://emoji.slack-edge.com/T0259UMNU/partyparrot/14100fc700824a61.gif)
