### ISSUE TITLE
spec's test suite

### ISSUE THREAD

**Issue by koresar** [stampit-org/stamp-specification#78]
Quoting @troutowicz 
> Something I'd like to see before v1.0 is the ability to import the spec's test suite into a spec related project. Right now I'm using a copied version for react-stamp. If I recall right, the only change I required was a different compose import path in each test file.

I'll implement that as part of this project. JFYI this project is going to be published to the NPM, and the test suite is the main reason to do that.

**Comment by troutowicz** [comment]
:+1: Thanks @koresar.

**Comment by ericelliott** [comment]
:+1:

**Comment by koresar** [comment]
Continue discussion in #80.
