### ISSUE TITLE
Descriptor name consistency

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/stamp-specification#9]
* `references` - A set of properties that will be added to new object instances by assignment.
* `deepProperties` - A set of properties that will be added to new object instances by assignment with deep property merge.
* `staticProperties` - A set of static properties that will be copied by assignment to the stamp.
* `propertyDescriptors` - A set of object property descriptors used for fine-grained control over object property behaviors

One of these names is not like the others. I think `references` needs to be renamed to `properties`. Assign by reference is default behavior in JavaScript. I don't think we need to be so explicit about it in the name. `deepProperties` provides the distinction we need to tell them apart. In other words, I propose this, for consistency:

* `properties` - A set of properties that will be added to new object instances by assignment.
* `deepProperties` - A set of properties that will be added to new object instances by assignment with deep property merge.
* `staticProperties` - A set of static properties that will be copied by assignment to the stamp.
* `propertyDescriptors` - A set of object property descriptors used for fine-grained control over object property behaviors

**Comment by troutowicz** [comment]
:+1:  for `references` -> `properties`

**Comment by JosephClay** [comment]
:+1: for me as well

**Comment by koresar** [comment]
What I hate about them is their really long-long names.

Just imagine people creating stamps:
```js
compose({
  deepProperties: ...
  staticProperties: ...
  propertyDescriptors: ...
});
```
I'd kill myself typing that much.

**Comment by koresar** [comment]
GUYS! Please, hear what I'm saying:

The `compose` function should accept a descriptor. The `compose` function is the core of the standard. It's gonna be used by many many developers. The arguments passed to the `compose` function must be short, as short as possible. The proposed long names for the descriptor properties are performance-killing features.

The `compose({ xxx })` arguments must not differ from the `stamp.compose.xxx` properties!

**Comment by JosephClay** [comment]
@koresar I can agree that I would not like to write these long property names...however `references` is the same length as `properties` :)

> The proposed long names for the descriptor properties are performance-killing features.

How so?

**Comment by koresar** [comment]
`assign` sound shorter. Moreover, there are longer names to pay more attention to.

**Comment by koresar** [comment]
> The proposed long names for the descriptor properties are performance-killing features.

Sorry. I missed the word. Should have been "development performance killing".

**Comment by ericelliott** [comment]
> What I hate about them is their really long-long names.

This is not the place to optimize for developer friendliness, because **the spec is not the end user developer API -- the utility functions are.**

This is the descriptor spec, **not the user interface**.

In other words, the people who create a stamp utility will have to deal with these names *only while developing the utility*.

End users will not need to use these names directly unless they want to ignore the utility functions.

**Comment by ericelliott** [comment]
What we are optimizing for in the stamp descriptor specification is (in order of importance):

1. Consistency with the existing JavaScript built-in APIs
2. Clarity

Conciseness / number of chars to type is a long, lagging, distant last place.

**Comment by koresar** [comment]
Please, do avoid rush closing issues while a dicussion is still lvie and vibrant. I have things to clarify. Thank you in advance.

**Comment by koresar** [comment]
And I clicked the wrong button. Pardon. :)

**Comment by ericelliott** [comment]
Hmm. I didn't close this issue. I closed #6.  =)

**Comment by koresar** [comment]
See stampit for example. It **supports promises**, but it **does not require any specific promise library**. How is that possible? Because `.then(onResolve, onReject)` returns a self-sufficient object. It which does not require any utility functions.

When talking about code I prefer to show code.

Here is your proposal, Eric:
```js
import merge from 'composable';
someFunction.compose(merge({ something: 42 }));
```

Here is my proposal:
```js
someFunction.compose({merge: { something: 42 }});
```

Do you see the difference? It's this `import` line is the difference. Moreover, you are forcing people to `npm install composable --save` and one more dependency in the project: `"composable": "^1.0.0"`

Now you see my point? It's not about number of character to type. It's about high coupling.

**Comment by koresar** [comment]
Take [mocha](https://github.com/mochajs/mocha/) for example. It supports promises. 
```js
it('bla', () => { return new Promise(); });
```
But **it does not depend on any promise implementation**. Check out its [dependencies](https://github.com/mochajs/mocha/blob/master/package.json#L276).

# Let's not force people to install any third party modules in order to compose stamps.

**Comment by ericelliott** [comment]
> Here is my proposal:
```js
someFunction.compose({merge: { something: 42 }});
```

The problem with this is that `merge` is a collection. It's not a collection of `merges`, though. It's a collection of **properties to merge**. In other words, while it does read pretty nicely, it is not self-documenting or descriptive of what the collection contains.

It also does not match the naming conventions of the existing JavaScript API.

You left out part of my proposal:

```js
someFunction.compose({deepProperties: { something: 42 }});
```

While this doesn't have the neat imperative API or conciseness that your proposal has, it is self-descriptive, and it is consistent with the existing official JS specification. The relevant API in this case is the [Object.defineProperties() API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties) which establishes the convention of calling properties "properties" for the purpose of property-related specs. This convention carries through:

* [getOwnPropertyDescriptor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor)
* [getOwnPropertyNames](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames)
* [getOwnPropertySymbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols)
* [hasOwnProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty)
* [propertyIsEnumerable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/propertyIsEnumerable)

Note the things all of these have in common:

* Methods all use verbs
* Properties are all referred to as nouns
* All optimized to be self explanatory rather than concise
* Stampit utility functions could potentially present a much nicer user interface to deal with these

The utility functions are where we make dealing with descriptors concise, because that is the API that developers will use most often.

**Comment by ericelliott** [comment]
> Let's not force people to install any third party modules in order to compose stamps.

We won't. That's why the core utilities are called "core utilities" rather than "extras".

**Comment by koresar** [comment]
So, you believe the utilities must be part of the standard?

When talking about code I prefer code. Would you please provide an example how you see people will:
1) Import core utilities (both CommonJS and ES6 ways).
2) Use core utilities.

Otherwise, I recognize the core utilities as useless bloat. We'll never make it if the standard is overblown with useless stuff.

**Comment by ericelliott** [comment]
I think the core utilities should be included in stampit:

```js
import stampit from 'stampit';

const myMergeStamp = stampit.merge(someDeepProps);
```

In the ECMAScript spec:

```
const merge = Object.Stamp.merge;
```

Which TC-39 will probably want to change to `Object.Stamp.mergeDeepProperties()`.

The point is, this really has nothing to do with the names of the stamp descriptors, because most users will probably chose to use utility functions rather than work with stamp descriptors directly, for the same reason that a lot of people choose to use `$()` instead of `document.querySelectorAll()`.

**Comment by koresar** [comment]
What would be ES5-compatible usage?

**Comment by ericelliott** [comment]
```js
var stampit = require('stampit');

const myMergeStamp = stampit.merge(someDeepProps);
```

**Comment by koresar** [comment]
I have many modules like this:

```shell
$ npm i base-stamp
```
```js
module.exports = require('base-stamp')
  .props(...)
  .static(...)
  .methods(...);
```
They all do not depend on stampit.

Do you say that I would need to write?
```js
module.exports = require('base-stamp').compose(
  deepProperies: ..., 
  staticProperties: ...
  methods: ...
});
```

**Comment by ericelliott** [comment]
> They all do not depend on stampit.

If our effort succeeds and stamps become part of the JavaScript specification, you won't have to depend on any libraries at all. That's what my real aim is. Look at the long-term gain, not the short time keystroke savings.

Also, there's a reason I called some utilities **core** utilities. I'm not convinced we need to make them part of the `stamp.compose.*` spec just because you sometimes like to work with stamps without directly requiring stampit, but I do think it's worth adding them to the default stampit export so you don't have to jump through hoops to use them. 

```js
module.exports = require('base-stamp').compose(
  deepProperies: ..., 
  staticProperties: ...
  methods: ...
});
```

If you'd rather do that than `var stampit = require('stampit');` that's your prerogative, but I don't think adding a require statement to get shortcuts is a terrible thing to ask of developers. Frankly this is just a few more keystrokes than your proposal, even if you do prefer to work with descriptors directly.

Let's look alternative:

```js
var s = require('stampit');

module.exports = require('base-stamp').compose(
  s.merge( ...), 
  s.addStatic( ...), // better than assignStatic?
  s.addMethods( ... ) // better than methods?
});
```

Even better:

```js
import { merge, addStatic, addMethods } from 'stampit';
import base from 'base-stamp';

export default module.exports = base.compose(
  merge( ...), 
  addStatic( ...), // better than assignStatic?
  addMethods( ... ) // better than methods?
});
```

Alternatively, we could also supply a fluent API and make it more familiar to Stampit users:

```js
import base from 'base-stamp';

export default base.chain()
  .merge() // instead of returning the stamp, these would return the chain API
  .addStatic()
  .addMethods()
  .stamp(); // return the actual stamp
```

The only downside to the chain API I can think of is that it may hard to sell to TC-39.

But, even if that doesn't fly...

## Do I think a self-documenting API is worth a few extra keystrokes per stamp definition?

**Absolutely.**


## Some ways to rewrite your previous example

```js
var stampit = require('stampit');
var merge = stampit.merge;

someFunction.compose( merge({ something: 42 }) );
```

```js
import { stampit, merge } from 'stampit';

someFunction.compose( merge({ something: 42 }) );
```

One import:

```js
import stampit from 'stampit';

someFunction.compose( stampit.merge({ something: 42 }) );
```

**Comment by ericelliott** [comment]
One more thing.

## We're not optimizing for ES5. ES6 is the current standard.

If your team is still using ES5, I suggest you start planning the upgrade path so you don't get left behind.

**Comment by koresar** [comment]
Or npm modules are ES5 compatible (most written in ES6 though) bacause in large orgs people need to have coffeescript, ES5, ES6, iOS and IE9 support.

**Comment by ericelliott** [comment]
Yep. That's why we compile, but it's not what I'm talking about.

What I'm saying is that you shouldn't look at the ES5 examples to see if the API is friendly enough. You should look at the ES6 examples, because about half of the developers we surveyed 2 months ago were already using ES6... relatively few people will still be authoring code in ES5 by the time this spec becomes relevant to any project outside Stampit.

**Comment by JosephClay** [comment]
I was going to argue *for* @koresar's point last night...what if I want to write composables by hand? It would be hard and ugly! But there are many [cumbersome][1] [native][2] [methods][3] in [javascript][4]. 

With this being a spec, I don't mind the long names. Any reasonable implementation is going to abstract that away (and let you define your own shortcuts). Any user who doesn't want to use a lib and wants to use the spec itself still can, it'll just be cumbersome.

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty
[2]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames
[3]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor
[4]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

**Comment by koresar** [comment]
After a quick chat we agreed to:
1) leave the long names as they are list on the top. All changes arealready merged to the .md and .js files accordingly.
2) we rename *"core utililities"* to **"optional extra utilities"**. Also can be referenced as "additional utilities" or "stampit utilities". The utilities should not be part of the standard, although can be referenced as "handy tools".
