### ISSUE TITLE
Does single stamp needs multiple initializers?

### ISSUE THREAD

**Issue by FredyC** [stampit-org/stamp-specification#90]
I am wondering if it wouldn't be worth it have singular `initializer` along the `initializers`. Considering that stamps are usually rather small, might be rather rare to actually have multiple initializers there. Can we talk about some use cases where it might be beneficial to split initializer code into multiple functions within single stamp?

**Comment by ericelliott** [comment]
Are you suggesting that we remove the ability to assign multiple initializers to a single stamp? **Why?**

If you use as `init()` helper function that can take a single function as an argument, does it make any difference at all to the usability?

**Comment by koresar** [comment]
With stampit v3 you can have singular initializer:
```js
stampit({ init: function () {} });
```

**Comment by FredyC** [comment]
> Are you suggesting that we remove the ability to assign multiple initializers to a single stamp? Why?

Yea sorry, I have ability to express my thoughts rather badly :) I kinda wrote this before I had fully realized difference between descriptor and that stampit adds these functions there. It was meant like there could be both of these in spec. Nevermind me :)
