### ISSUE TITLE
Use smaller assign instead of lodash.assign

### ISSUE THREAD

**Issue by FredyC** [stampit-org/stamp-specification#95]
Another finding [regarding bundle size](https://github.com/stampit-org/stampit/issues/212).

At first it might seem that `lodash.assign` is winner here with 6.8K minified vs 7.6K for polyfilled `Object.assign`. However there are two main reasons why would I stick to `Object.assign`.

 * It's standardized so eventually need for polyfill may begone (essentially [only IE11, old Safari and Android](https://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign) needs it)
 * It has support for Symbol included thus solving #86 in most cases. If lodash ever adds support for it, I am sure that size will go up much more.

**Comment by koresar** [comment]
I would drop lodash.assign altogether for smaller polyfils like this: https://github.com/sindresorhus/object-assign/blob/master/index.js

**Comment by FredyC** [comment]
Hm, yea I guess might be another option, however consider that someone wouldn't be able to make a build with just native `Object.assign` thus effectively removing any support code for it. For someone targeting only major browsers it might be another 1K down in size. Although I am not sure about performance of native implementations, heard some stories that polyfill is usually faster...

**Comment by koresar** [comment]
AFAIK `Object.assign` in the latest v8 versions (node v6 at least) is as fast as lodash or polyfills. The rest native implementation are slower though.

Premature optimizations is the root of all evil. I would prefer us to optimize 
* to run in as many environments as possible, and 
* to have as less as possible dependencies.

**Comment by FredyC** [comment]
I think that general idea should be to give consumer ability to choose if he wants use polyfill or native solution depending on his target platform. If we just add there some external implementation we are taking any choice from him and adding another dependency to the package.

**Comment by koresar** [comment]
Yep. Agree. It's good we have the rollup now! :)

**Comment by FredyC** [comment]
Alright, so based on investigation in #97 I am withdrawing this. As much as it would be nice to use standardized functions, it's still very problematic in cases when it has to be polyfilled. I think that using https://github.com/sindresorhus/object-assign/blob/master/index.js might be best solution after all.

**Comment by FredyC** [comment]
I suppose we can close this as well since it's not needed anymore to minimize bundle size.
